// src/pages/PrivacyPolicyPage.tsx
import { Link } from "react-router-dom";

function PrivacyPolicyPage() {
  return (
    <div className="main-content legal-content">
      <Link to="/" className="back-button" style={{ textDecoration: "none", display: "inline-block" }}>
        &larr; Back to Home
      </Link>
      <h1 className="section-title text-center">Privacy Policy for Collectiq</h1>
      <section className="section">
        <p className="text-base mb-4">
          <strong>Effective Date: August 23, 2024</strong>
        </p>

        <p className="text-base mb-4">
          Collectiq ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how
          Collectiq, an application designed for users to track, manage, and share their collections, collects, uses,
          discloses, and safeguards your information when you use our mobile application (the "App").
        </p>

        <h2>1. Information We Collect</h2>
        <p className="text-base mb-4">We collect information that helps us provide and improve our services.</p>
        <ul className="list-disc pl-5 mb-4 space-y-2">
          <li>
            <strong>Account Information:</strong> When you create an account, we collect your email address, password
            (hashed securely by Supabase Auth), and the username you choose. We also store a unique user ID generated by
            Supabase.
          </li>
          <li>
            <strong>Profile Information:</strong> You may choose to provide additional information for your user
            profile, such as a full name, a short biography, and an avatar image.
          </li>
          <li>
            <strong>Collection Data:</strong> Information related to your collections, including collection names,
            descriptions, images, public/private status, and details about items within those collections.
          </li>
          <li>
            <strong>Item Data:</strong> Details about individual items within your collections, such as item names,
            descriptions, and images.
          </li>
          <li>
            <strong>User Item Data:</strong> This includes your personal data associated with a specific item in a
            collection, such as its "owned" status, private notes, purchase price, and any photos you upload of your
            specific items (e.g., photos of *your* stamp, not a generic image for the item type). This data is
            considered highly personal.
          </li>
          <li>
            <strong>Interaction Data:</strong> Information about your interactions within the App, such as other users'
            collections you choose to follow (bookmarks), and other users you choose to follow.
          </li>
          <li>
            <strong>Usage Data:</strong> We may collect anonymous, non-identifiable analytical data about how you access
            and use the App, such as device type, operating system, IP address (for security and troubleshooting, not
            for identification), and general interaction patterns. This data is used for internal analysis to improve
            the App and is not linked to your personal identity.
          </li>
        </ul>

        <h2>2. How We Collect Information</h2>
        <ul className="list-disc pl-5 mb-4 space-y-2">
          <li>
            <strong>Directly from You:</strong> When you register for an account, create or update your profile, add new
            collections or items, upload user item photos, or interact with features like following.
          </li>
          <li>
            <strong>Automatically:</strong> Through your use of the App, as usage data and technical information is
            logged to understand performance, identify issues, and improve features.
          </li>
        </ul>

        <h2>3. How We Use Your Information</h2>
        <p className="text-base mb-4">
          We use the information we collect for various purposes to provide and improve the Collectiq service:
        </p>
        <ul className="list-disc pl-5 mb-4 space-y-2">
          <li>To provide, operate, and maintain the functionality of the App.</li>
          <li>To create, manage, and secure your user account.</li>
          <li>
            To enable you to create, manage, and display your collections, items, and personalized user item data.
          </li>
          <li>To allow you to discover and follow other users' public collections and profiles.</li>
          <li>To personalize your experience within the App, such as displaying relevant content or suggestions.</li>
          <li>To communicate with you regarding your account, updates to the App, and respond to your inquiries.</li>
          <li>
            To monitor and analyze usage patterns, diagnose technical problems, and optimize the App's performance and
            user experience.
          </li>
          <li>
            To detect, prevent, and address potential fraudulent activities, security breaches, or other harmful
            content.
          </li>
          <li>To comply with legal obligations and enforce our Terms and Conditions.</li>
        </ul>

        <h2>4. Data Storage and Security</h2>
        <p className="text-base mb-4">
          Your data is stored in a secure cloud database powered by <strong>Supabase</strong>. Supabase employs
          industry-standard security measures, including encryption at rest and in transit (via HTTPS/TLS), robust
          access controls, and regular security audits. While we strive to use commercially acceptable means to protect
          your personal information, no method of transmission over the Internet or electronic storage is 100% secure.
          Therefore, we cannot guarantee its absolute security.
        </p>
        <p className="text-base mb-4">
          We use <strong>Supabase Auth</strong> for user authentication, which handles password hashing and session
          management securely.
        </p>

        <h2>5. Data Retention</h2>
        <p className="text-base mb-4">
          We retain your personal information for as long as your account is active or as needed to provide you with the
          App's services, comply with our legal obligations, resolve disputes, and enforce our agreements. If you choose
          to delete your account, we will initiate steps to delete your data as described in the "Your Rights" section.
        </p>

        <h2>6. Disclosure of Your Information</h2>
        <p className="text-base mb-4">We may share your information in the following situations:</p>
        <ul className="list-disc pl-5 mb-4 space-y-2">
          <li>
            <strong>With Your Consent:</strong> We may disclose your personal information for any purpose with your
            explicit consent. For example, when you mark a collection as "public," it becomes visible to other users.
          </li>
          <li>
            <strong>Service Providers:</strong> We use Supabase as our backend service provider for database,
            authentication, and file storage. Your data is shared with Supabase solely for the purpose of operating the
            App and is subject to their privacy and security policies. We do not use any other third-party data
            collectors (e.g., Google Analytics, Firebase Analytics, Mixpanel, etc.).
          </li>
          <li>
            <strong>Legal Requirements:</strong> We may disclose your information if required to do so by law or in
            response to valid requests by public authorities (e.g., a court order or government agency).
          </li>
          <li>
            <strong>To Protect Rights and Property:</strong> We may disclose information when we believe it is necessary
            to investigate, prevent, or take action regarding potential violations of our policies, suspected fraud,
            situations involving potential threats to the safety of any person, or as evidence in litigation in which we
            are involved.
          </li>
          <li>
            <strong>Business Transfers:</strong> In the event of a merger, acquisition, or sale of all or a portion of
            our assets, your information may be transferred as part of that transaction.
          </li>
          <li>
            <strong>Aggregated/Anonymized Data:</strong> We may share aggregated or de-identified information that
            cannot reasonably be used to identify you.
          </li>
        </ul>

        <h2>7. Your Rights</h2>
        <p className="text-base mb-4">
          Depending on your location and applicable laws (such as GDPR or CCPA), you may have the following rights
          regarding your personal data:
        </p>
        <ul className="list-disc pl-5 mb-4 space-y-2">
          <li>
            <strong>Right to Access:</strong> You have the right to request copies of your personal data we hold.
          </li>
          <li>
            <strong>Right to Rectification:</strong> You have the right to request that we correct any information you
            believe is inaccurate or complete information you believe is incomplete. You can mostly do this directly
            within the App by editing your profile, collections, and items.
          </li>
          <li>
            <strong>Right to Erasure (Right to Be Forgotten):</strong> You have the right to request that we erase your
            personal data under certain conditions. This includes the ability to delete your entire Collectiq account
            through the App settings. Please note that deleting your account will remove your profile, collections,
            items, and any user item data. This action is irreversible.
          </li>
          <li>
            <strong>Right to Restrict Processing:</strong> You have the right to request that we restrict the processing
            of your personal data under certain conditions.
          </li>
          <li>
            <strong>Right to Object to Processing:</strong> You have the right to object to our processing of your
            personal data under certain conditions.
          </li>
          <li>
            <strong>Right to Data Portability:</strong> You have the right to request that we transfer the data that we
            have collected to another organization, or directly to you, under certain conditions.
          </li>
        </ul>
        <p className="text-base mb-4">
          To exercise any of these rights, please contact us at the email address provided below. We will respond to
          your request within a reasonable timeframe as required by applicable law.
        </p>

        <h2>8. Children's Privacy (COPPA Compliance)</h2>
        <p className="text-base mb-4">
          Collectiq is not intended for children under the age of 13. We do not knowingly collect personally
          identifiable information from children under 13. If you become aware that a child has provided us with
          personal information without parental consent, please contact us, and we will take steps to remove such
          information and terminate the child's account.
        </p>

        <h2>9. Changes to This Privacy Policy</h2>
        <p className="text-base mb-4">
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new
          Privacy Policy on this page and updating the "Effective Date" at the top. You are advised to review this
          Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted
          on this page.
        </p>

        <h2>10. Contact Us</h2>
        <p className="text-base mb-4">
          If you have any questions or concerns about this Privacy Policy, please contact us at:
        </p>
        <p className="text-base mb-4">
          Email: <a href="mailto:sguo114@gmail.com">sguo114@gmail.com</a>
        </p>
      </section>
    </div>
  );
}

export default PrivacyPolicyPage;
